/* The following code was generated by JFlex 1.7.0 */

package com.tpi.teoi;
import java_cup.runtime.Symbol;
import java_cup.runtime.*;
import java.util.*;
import jflex.sym;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Lexico.flex</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\45\1\13\1\14\1\13\1\13\22\0\1\45\1\0\1\0"+
    "\11\0\1\1\3\0\12\3\1\46\2\0\1\47\3\0\1\26\1\2"+
    "\1\24\1\22\1\23\1\2\1\41\1\2\1\32\2\2\1\25\1\42"+
    "\1\34\1\33\1\40\1\2\1\27\1\30\1\31\6\2\1\43\1\0"+
    "\1\44\1\0\1\4\1\0\1\11\1\2\1\7\1\5\1\6\1\2"+
    "\1\36\1\2\1\17\2\2\1\10\1\37\1\21\1\20\1\35\1\2"+
    "\1\12\1\15\1\16\6\2\12\0\1\14\u1fa2\0\1\14\1\14\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\2\3\1\5\4\3"+
    "\1\6\1\7\1\1\6\3\1\10\46\3\1\0\3\3"+
    "\1\0\3\3\1\0\1\3\1\0\1\3\1\0\3\3"+
    "\1\0\3\3\1\0\1\3\1\0\1\3\1\0\3\3"+
    "\1\0\3\3\1\0\1\3\1\0\1\3\1\0\1\3"+
    "\1\0\1\3\1\0\1\3\1\0\1\3\1\0\1\3"+
    "\1\0\1\3\1\0\1\3\1\0\1\3\1\0\1\3"+
    "\1\0\1\3\1\0\1\3\1\0\1\3\1\0\1\3"+
    "\1\0\1\3\1\0\1\3\1\0\1\3\1\0\1\3"+
    "\1\0\1\3\1\0\1\3\1\0\1\3\1\0\1\3"+
    "\1\0\1\3\1\0\1\3\1\0\1\3\1\0\1\3"+
    "\1\0\1\3\1\0\1\3\1\0\1\3\1\0\1\3"+
    "\1\0\1\3\1\0\1\3\1\0\1\3\2\11\1\0"+
    "\1\3\1\0\1\3\1\0\1\3\1\0\1\3\2\12"+
    "\1\0\1\3\1\0\1\3\1\0\1\3\1\0\1\3"+
    "\1\0\1\3\1\0\1\3\1\0\1\3\1\0\1\3"+
    "\2\13\2\14";

  private static int [] zzUnpackAction() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\50\0\120\0\170\0\240\0\310\0\50"+
    "\0\360\0\u0118\0\u0140\0\u0168\0\50\0\50\0\u0190\0\u01b8"+
    "\0\u01e0\0\u0208\0\u0230\0\u0258\0\u0280\0\50\0\u02a8\0\u02d0"+
    "\0\u02f8\0\u0320\0\u0348\0\u0370\0\u0398\0\u03c0\0\u03e8\0\u0410"+
    "\0\u0438\0\u0460\0\u0488\0\u04b0\0\u04d8\0\u0500\0\u0528\0\u0550"+
    "\0\u0578\0\u05a0\0\u05c8\0\u05f0\0\u0618\0\u0640\0\u0668\0\u0690"+
    "\0\u06b8\0\u06e0\0\u0708\0\u0730\0\u0758\0\u0780\0\u07a8\0\u07d0"+
    "\0\u07f8\0\u0820\0\u0848\0\u0870\0\u0898\0\u08c0\0\u08e8\0\u0910"+
    "\0\u0938\0\u0960\0\u0988\0\u09b0\0\u09d8\0\u0a00\0\u0a28\0\u0a50"+
    "\0\u0a78\0\u0aa0\0\u0ac8\0\u0af0\0\u0b18\0\u0b40\0\u0b68\0\u0b90"+
    "\0\u0bb8\0\u0be0\0\u0c08\0\u0c30\0\u0c58\0\u0c80\0\u0ca8\0\u0cd0"+
    "\0\u0cf8\0\u0d20\0\u0d48\0\u0d70\0\u0d98\0\u0dc0\0\u0de8\0\u0e10"+
    "\0\u0e38\0\u0e60\0\u0e88\0\u0eb0\0\u0ed8\0\u0f00\0\u0f28\0\u0f50"+
    "\0\u0f78\0\u0fa0\0\u0fc8\0\u0ff0\0\u1018\0\u1040\0\u1068\0\u1090"+
    "\0\u10b8\0\u10e0\0\u1108\0\u1130\0\u1158\0\u1180\0\u11a8\0\u11d0"+
    "\0\u11f8\0\u1220\0\u1248\0\u1270\0\u1298\0\u12c0\0\u12e8\0\u1310"+
    "\0\u1338\0\u1360\0\u1388\0\u13b0\0\u13d8\0\u1400\0\u1428\0\u1450"+
    "\0\u1478\0\u14a0\0\u14c8\0\u14f0\0\u1518\0\u1540\0\u1568\0\u1590"+
    "\0\u15b8\0\u15e0\0\u1608\0\u1630\0\u1658\0\u1680\0\u16a8\0\u16d0"+
    "\0\u16f8\0\u1720\0\u1748\0\u1770\0\u1798\0\u17c0\0\u17e8\0\u1810"+
    "\0\50\0\120\0\u1838\0\u1860\0\u1888\0\u18b0\0\u18d8\0\u1900"+
    "\0\u1928\0\u1950\0\50\0\120\0\u1978\0\u19a0\0\u19c8\0\u19f0"+
    "\0\u1a18\0\u1a40\0\u1a68\0\u1a90\0\u1ab8\0\u1ae0\0\u1b08\0\u1b30"+
    "\0\u1b58\0\u1b80\0\u1ba8\0\u1bd0\0\50\0\120\0\50\0\120";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\1\6\1\7\4\4"+
    "\1\10\1\2\5\4\1\11\1\12\11\4\1\13\2\4"+
    "\1\14\2\4\1\15\1\16\1\10\1\17\1\2\52\0"+
    "\11\4\2\0\26\4\10\0\1\5\46\0\4\4\1\20"+
    "\4\4\2\0\26\4\7\0\11\4\2\0\4\4\1\21"+
    "\21\4\7\0\11\4\2\0\6\4\1\22\17\4\7\0"+
    "\11\4\2\0\17\4\1\23\6\4\7\0\10\4\1\24"+
    "\2\0\26\4\7\0\11\4\2\0\12\4\1\25\13\4"+
    "\54\0\1\26\2\0\5\4\1\27\3\4\2\0\26\4"+
    "\7\0\3\4\1\30\5\4\2\0\26\4\7\0\11\4"+
    "\2\0\7\4\1\31\16\4\7\0\11\4\2\0\5\4"+
    "\1\32\20\4\7\0\11\4\2\0\3\4\1\33\22\4"+
    "\7\0\11\4\2\0\16\4\1\34\7\4\7\0\6\4"+
    "\1\35\2\4\2\0\26\4\7\0\3\4\1\36\5\4"+
    "\2\0\20\4\1\37\5\4\7\0\11\4\2\0\10\4"+
    "\1\40\15\4\7\0\11\4\2\0\5\4\1\41\15\4"+
    "\1\42\2\4\7\0\11\4\2\0\21\4\1\43\4\4"+
    "\7\0\11\4\2\0\24\4\1\44\1\4\7\0\7\4"+
    "\1\45\1\4\2\0\26\4\7\0\4\4\1\46\4\4"+
    "\2\0\26\4\7\0\10\4\1\47\2\0\26\4\7\0"+
    "\11\4\2\0\11\4\1\50\14\4\7\0\11\4\2\0"+
    "\6\4\1\51\17\4\7\0\11\4\2\0\12\4\1\52"+
    "\13\4\7\0\10\4\1\53\2\0\26\4\7\0\11\4"+
    "\2\0\12\4\1\54\13\4\7\0\10\4\1\55\2\0"+
    "\26\4\7\0\5\4\1\56\3\4\2\0\26\4\7\0"+
    "\11\4\2\0\3\4\1\57\22\4\7\0\11\4\2\0"+
    "\12\4\1\60\13\4\7\0\11\4\2\0\7\4\1\61"+
    "\16\4\7\0\11\4\2\0\16\4\1\62\7\4\7\0"+
    "\7\4\1\63\1\4\2\0\26\4\7\0\11\4\2\0"+
    "\11\4\1\64\14\4\7\0\4\4\1\65\4\4\2\0"+
    "\26\4\7\0\6\4\1\66\2\4\2\0\26\4\7\0"+
    "\11\4\2\0\21\4\1\67\4\4\7\0\11\4\2\0"+
    "\6\4\1\70\17\4\7\0\11\4\2\0\10\4\1\71"+
    "\15\4\7\0\11\4\2\0\24\4\1\72\1\4\7\0"+
    "\11\4\2\0\22\4\1\73\3\4\7\0\11\4\2\0"+
    "\25\4\1\74\5\0\2\75\11\76\2\0\26\76\5\75"+
    "\2\0\7\4\1\77\1\4\2\0\26\4\7\0\10\4"+
    "\1\100\2\0\26\4\5\0\2\101\11\102\2\0\26\102"+
    "\5\101\2\0\11\4\2\0\11\4\1\103\14\4\7\0"+
    "\11\4\2\0\12\4\1\104\13\4\5\0\2\105\11\106"+
    "\2\0\26\106\5\105\2\107\11\110\2\0\26\110\5\107"+
    "\15\0\1\111\34\0\11\4\2\0\1\112\25\4\7\0"+
    "\10\4\1\113\2\0\26\4\7\0\7\4\1\114\1\4"+
    "\2\0\26\4\35\0\1\115\21\0\11\4\2\0\13\4"+
    "\1\116\12\4\7\0\11\4\2\0\12\4\1\117\13\4"+
    "\7\0\11\4\2\0\11\4\1\120\14\4\22\0\1\121"+
    "\34\0\11\4\2\0\1\122\25\4\35\0\1\123\21\0"+
    "\11\4\2\0\13\4\1\124\12\4\13\0\1\125\43\0"+
    "\4\4\1\126\4\4\2\0\26\4\7\0\4\4\1\127"+
    "\4\4\2\0\26\4\7\0\11\4\2\0\22\4\1\130"+
    "\3\4\30\0\1\131\26\0\11\4\2\0\6\4\1\132"+
    "\17\4\7\0\11\4\2\0\6\4\1\133\17\4\7\0"+
    "\11\4\2\0\25\4\1\134\13\0\1\135\43\0\4\4"+
    "\1\136\4\4\2\0\26\4\30\0\1\137\26\0\11\4"+
    "\2\0\6\4\1\140\17\4\14\0\1\141\42\0\5\4"+
    "\1\142\3\4\2\0\26\4\5\0\2\143\11\144\2\0"+
    "\26\144\5\143\2\145\11\146\2\0\26\146\5\145\24\0"+
    "\1\147\25\0\11\4\2\0\7\4\1\150\16\4\5\0"+
    "\2\151\11\152\2\0\26\152\5\151\2\153\11\154\2\0"+
    "\26\154\5\153\7\0\1\155\42\0\5\4\1\156\3\4"+
    "\2\0\26\4\31\0\1\157\25\0\11\4\2\0\7\4"+
    "\1\160\16\4\23\0\1\161\33\0\11\4\2\0\1\4"+
    "\1\162\24\4\22\0\1\163\34\0\11\4\2\0\1\164"+
    "\25\4\22\0\1\165\34\0\11\4\2\0\1\166\25\4"+
    "\36\0\1\167\20\0\11\4\2\0\14\4\1\170\11\4"+
    "\35\0\1\171\21\0\11\4\2\0\13\4\1\172\12\4"+
    "\35\0\1\173\21\0\11\4\2\0\13\4\1\174\12\4"+
    "\23\0\1\175\33\0\11\4\2\0\1\4\1\176\24\4"+
    "\36\0\1\177\20\0\11\4\2\0\14\4\1\200\11\4"+
    "\24\0\1\201\32\0\11\4\2\0\2\4\1\202\23\4"+
    "\13\0\1\203\43\0\4\4\1\204\4\4\2\0\26\4"+
    "\13\0\1\205\43\0\4\4\1\206\4\4\2\0\26\4"+
    "\37\0\1\207\17\0\11\4\2\0\15\4\1\210\10\4"+
    "\30\0\1\211\26\0\11\4\2\0\6\4\1\212\17\4"+
    "\30\0\1\213\26\0\11\4\2\0\6\4\1\214\17\4"+
    "\24\0\1\215\32\0\11\4\2\0\2\4\1\216\23\4"+
    "\37\0\1\217\17\0\11\4\2\0\15\4\1\220\10\4"+
    "\25\0\1\221\31\0\11\4\2\0\3\4\1\222\22\4"+
    "\14\0\1\223\42\0\5\4\1\224\3\4\2\0\26\4"+
    "\14\0\1\225\42\0\5\4\1\226\3\4\2\0\26\4"+
    "\40\0\1\227\16\0\11\4\2\0\16\4\1\230\7\4"+
    "\31\0\1\231\25\0\11\4\2\0\7\4\1\232\16\4"+
    "\31\0\1\233\25\0\11\4\2\0\7\4\1\234\16\4"+
    "\25\0\1\235\31\0\11\4\2\0\3\4\1\236\22\4"+
    "\40\0\1\237\16\0\11\4\2\0\16\4\1\240\7\4"+
    "\26\0\1\241\30\0\11\4\2\0\4\4\1\242\21\4"+
    "\23\0\1\243\33\0\11\4\2\0\1\4\1\244\24\4"+
    "\23\0\1\245\33\0\11\4\2\0\1\4\1\246\24\4"+
    "\41\0\1\241\15\0\11\4\2\0\17\4\1\242\6\4"+
    "\36\0\1\247\20\0\11\4\2\0\14\4\1\250\11\4"+
    "\36\0\1\251\20\0\11\4\2\0\14\4\1\252\11\4"+
    "\26\0\1\253\30\0\11\4\2\0\4\4\1\254\21\4"+
    "\41\0\1\253\15\0\11\4\2\0\17\4\1\254\6\4"+
    "\24\0\1\255\32\0\11\4\2\0\2\4\1\256\23\4"+
    "\24\0\1\257\32\0\11\4\2\0\2\4\1\260\23\4"+
    "\37\0\1\261\17\0\11\4\2\0\15\4\1\262\10\4"+
    "\37\0\1\263\17\0\11\4\2\0\15\4\1\264\10\4"+
    "\25\0\1\265\31\0\11\4\2\0\3\4\1\266\22\4"+
    "\25\0\1\267\31\0\11\4\2\0\3\4\1\270\22\4"+
    "\40\0\1\271\16\0\11\4\2\0\16\4\1\272\7\4"+
    "\40\0\1\273\16\0\11\4\2\0\16\4\1\274\7\4"+
    "\26\0\1\275\30\0\11\4\2\0\4\4\1\276\21\4"+
    "\26\0\1\277\30\0\11\4\2\0\4\4\1\300\21\4"+
    "\41\0\1\275\15\0\11\4\2\0\17\4\1\276\6\4"+
    "\41\0\1\277\15\0\11\4\2\0\17\4\1\300\6\4"+
    "\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7160];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\4\1\1\11\4\1\2\11\7\1\1\11"+
    "\46\1\1\0\3\1\1\0\3\1\1\0\1\1\1\0"+
    "\1\1\1\0\3\1\1\0\3\1\1\0\1\1\1\0"+
    "\1\1\1\0\3\1\1\0\3\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\11\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\11\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\11\1\1\1\11"+
    "\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 172) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Caracter no permitido: <" + yytext() + "> en la linea " + yyline);
            } 
            // fall through
          case 13: break;
          case 2: 
            { System.out.println("Token COMA encontrado, Lexema "+ yytext());
            } 
            // fall through
          case 14: break;
          case 3: 
            { System.out.println("Token ID encontrado, Lexema "+ yytext());
            } 
            // fall through
          case 15: break;
          case 4: 
            { System.out.println("Token CONST_INT, encontrado Lexema "+ yytext());
            } 
            // fall through
          case 16: break;
          case 5: 
            { /* ignore */
            } 
            // fall through
          case 17: break;
          case 6: 
            { System.out.println("Token SQR_BRACKET_OPEN, encontrado Lexema "+ yytext());
            } 
            // fall through
          case 18: break;
          case 7: 
            { System.out.println("Token SQR_BRACKET_CLOSE, encontrado Lexema "+ yytext());
            } 
            // fall through
          case 19: break;
          case 8: 
            { System.out.println("Token ASIGN encontrado, Lexema "+ yytext());
            } 
            // fall through
          case 20: break;
          case 9: 
            { System.out.println("Token DEC, encontrado Lexema "+ yytext());
            } 
            // fall through
          case 21: break;
          case 10: 
            { System.out.println("Token START, encontrado Lexema "+ yytext());
            } 
            // fall through
          case 22: break;
          case 11: 
            { System.out.println("Token ENDDEC, encontrado Lexema "+ yytext());
            } 
            // fall through
          case 23: break;
          case 12: 
            { System.out.println("Token FINALIZE, encontrado Lexema "+ yytext());
            } 
            // fall through
          case 24: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
