
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.tpi.teoi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMMENT_BEG = 7;
  public static final int DISTINTO = 16;
  public static final int ENDDEC = 22;
  public static final int PUNTO_Y_COMA = 36;
  public static final int COMMENT = 9;
  public static final int EspacioBlanco = 6;
  public static final int PRIMER_NUMERO = 4;
  public static final int BRACKET_CLOSE = 41;
  public static final int WRITE = 46;
  public static final int AND = 13;
  public static final int IGUAL = 15;
  public static final int SQR_BRACKET_OPEN = 38;
  public static final int LETRA = 2;
  public static final int OR = 14;
  public static final int TYPE_INT = 10;
  public static final int CONST_FLOAT = 50;
  public static final int EXIT = 28;
  public static final int IF = 25;
  public static final int SIG_MAS = 31;
  public static final int ID = 47;
  public static final int KEY_CLOSE = 43;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MAYOR_I = 18;
  public static final int OP_DECLARE = 45;
  public static final int DIGITO = 3;
  public static final int COMA = 34;
  public static final int MENOR = 19;
  public static final int START = 23;
  public static final int OP_ASSIGN = 44;
  public static final int MENOR_I = 20;
  public static final int BRACKET_OPEN = 40;
  public static final int TYPE_FLOAT = 12;
  public static final int COM = 37;
  public static final int MAYOR = 17;
  public static final int ELSE = 29;
  public static final int PUNTO = 35;
  public static final int TYPE_STRING = 11;
  public static final int COMMENT_END = 8;
  public static final int TAKE = 27;
  public static final int CARACTERES_ESPECIALES = 5;
  public static final int WHILE = 26;
  public static final int FINALIZE = 24;
  public static final int KEY_OPEN = 42;
  public static final int CONST_STRING = 48;
  public static final int SIG_DIV = 32;
  public static final int SIG_MENOS = 30;
  public static final int DEC = 21;
  public static final int SQR_BRACKET_CLOSE = 39;
  public static final int CONST_INT = 49;
  public static final int SIG_MUL = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LETRA",
  "DIGITO",
  "PRIMER_NUMERO",
  "CARACTERES_ESPECIALES",
  "EspacioBlanco",
  "COMMENT_BEG",
  "COMMENT_END",
  "COMMENT",
  "TYPE_INT",
  "TYPE_STRING",
  "TYPE_FLOAT",
  "AND",
  "OR",
  "IGUAL",
  "DISTINTO",
  "MAYOR",
  "MAYOR_I",
  "MENOR",
  "MENOR_I",
  "DEC",
  "ENDDEC",
  "START",
  "FINALIZE",
  "IF",
  "WHILE",
  "TAKE",
  "EXIT",
  "ELSE",
  "SIG_MENOS",
  "SIG_MAS",
  "SIG_DIV",
  "SIG_MUL",
  "COMA",
  "PUNTO",
  "PUNTO_Y_COMA",
  "COM",
  "SQR_BRACKET_OPEN",
  "SQR_BRACKET_CLOSE",
  "BRACKET_OPEN",
  "BRACKET_CLOSE",
  "KEY_OPEN",
  "KEY_CLOSE",
  "OP_ASSIGN",
  "OP_DECLARE",
  "WRITE",
  "ID",
  "CONST_STRING",
  "CONST_INT",
  "CONST_FLOAT"
  };
}

