
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ejemplojavacup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_A = 5;
  public static final int OP_DIV = 9;
  public static final int OP_RESTA = 8;
  public static final int OP_SUMA = 7;
  public static final int EOF = 0;
  public static final int ASIGN = 4;
  public static final int CONST_INT = 3;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int OP_POR = 10;
  public static final int PAR_C = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "CONST_INT",
  "ASIGN",
  "PAR_A",
  "PAR_C",
  "OP_SUMA",
  "OP_RESTA",
  "OP_DIV",
  "OP_POR"
  };
}

